experimentName: iDAG_Te_real
trialConcurrency: 1
maxExperimentDuration: 72h
maxTrialNumber: 200
#choice: local, remote, pai, kubeflow
trainingService:
  platform: local
  gpuIndices: 3
  useActiveGpu: true
  maxTrialNumberPerGpu: 1
#choice: true, false
useAnnotation: false
searchSpace:
  dag_anneal_steps:
    _type: choice
    _value: [200, 400, 600, 800]
  temperature:
    _type: uniform
    _value: [0.01, 0.07]
  ema_ratio:
    _type: uniform
    _value: [0.99, 0.999]
  # lambda1:
  #   _type: uniform
  #   _value: [0.01, 1.0]
  lambda2:
    _type: uniform
    _value: [0.01, 1.0]
  weight_nu:
    _type: uniform
    _value: [0.0, 2.0]
  weight_mu:
    _type: uniform
    _value: [0.0, 2.0]
  
tuner:
  #choice: TPE, Random, Anneal, Evolution
  name: TPE
  classArgs:
    #choice: maximize, minimize
    optimize_mode: maximize
trialCommand: python nni_train_all.py real0 --algorithm iDAG --data_dir /data/hzn/TransferLearning/SWAD/data --dataset DomainNet --output_dir ./train_output --test_envs 4 --steps 15000 --checkpoint_freq 500 --batch_size 32
trialCodeDirectory: ..
trialGpuNumber: 1
